### PR TITLE
ESP32

### PR DESCRIPTION
**Pull request by Tnze**
just turn to use the ESP32's API to do the same thing.

### CODE REVIEW

**Comment by 13r1ckz** [comment]
rigardu la nomon de la repo. ĝi diras esp8266 ne esp32 do tial la repo ne subtenas esp32

**Comment by Tnze** [comment]
那我是应该开一个分支或者怎么样？

**Comment by spacehuhn** [comment]
Thanks for the PR. I think the best way is to fork this repositoy and apply your changes and I will link to it in the readme.

**Comment by Tnze** [comment]
Nice idea~, I have done what you said: https://github.com/Tnze/esp32_beaconSpam
By the way, is that error "wifi: out of memory" a normal phenomenon?

**Pull request closed without merging**
